const MIN_PHONE_LEN = 10
const MAX_PHONE_LEN = 11
const DEFAULT_ERROR_MESSAGE = 'Algo deu errado!'
const INVALID_EMAIL_MESSAGE = 'Email inválido'

export {
  MAX_PHONE_LEN,
  MIN_PHONE_LEN,
  DEFAULT_ERROR_MESSAGE,
  INVALID_EMAIL_MESSAGE
}
