name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches: [ "main" ]

jobs:
  lint:
    name: Lint & Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install node
        uses: actions/setup-node@v3
        with:
          version: '16'
          
      - name: Install yarn
        run: npm install --global yarn
        
      - name: Install packages
        run: yarn install --frozen-lockfile
        
      - name: Run lint and prettier
        run: yarn lint
        
  test:
    needs: lint
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          version: '16'

      - name: Install yarn
        run: npm install --global yarn
      
      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn test
